### PR TITLE
Re enable test running using graaljs

### PR DESCRIPTION
**Pull request by pmlopes**
Currently we aren't running any tests. This PR will ensure we run the tests against es4x.

The PR will require a few prerequisites:

1. The PR on es4x https://github.com/reactiverse/es4x/pull/338 must be merged

This is because the verticle factory and future APIs have changed on core and they need to be properly aligned.

### CODE REVIEW

**Comment by vietj** [comment]
we cannot depend on es4x for testing because that creates a circular dependency.

we  simply need to use GraalVM to run tests like es4x does.

**Comment by pmlopes** [comment]
That is not so trivial because graaljs doesn't have a module loader (that's what es4x is doing + verticle factory).

If the api is stable we can use es4x built with a milestone release and excluding the vertx core dependency. This way this project defines the right dependencies.

**Comment by vietj** [comment]
I would like only this to be tested without verticles, i.e we run plain javascript with GraalJS and test service proxies.

Or perhaps then we simply drop this project too.

**Comment by pmlopes** [comment]
Wait, I see another way to test this just with graaljs. We generate universal modules, which means they should be able to be used without a loader too. 

Actually the generated code is wrong for this case. I can fix it and drop the dependency on es4x.

**Comment by pmlopes** [comment]
@vietj @slinkydeveloper I've updated the PR, it only depends on `graaljs` for running the tests now. I also noted a bug on the template where the `UMD` module was not being generated correctly (it always assumed `commonJS`. 

With the fix of the template we can just load manually the scripts into the script engine context on the right order and execute the test.

**Review by slinkydeveloper — APPROVED** [review]

**Comment by vietj** [comment]
can we get this executed in Travis @pmlopes ?

**Comment by pmlopes** [comment]
Yes, it can run with (openjdk 8 or up) or graalvm. I'll add it to the PR too.

**Comment by pmlopes** [comment]
https://travis-ci.org/github/vert-x3/vertx-sockjs-service-proxy/builds/678586452

**Review by vietj — APPROVED** [review]

**Pull request merged**
